TestShop.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestShop.Application.Models.Product;
using TestShop.Application.ServiceInterfaces;
using TestShop.CrossCutting.Enums;

namespace TestShop.Web.Controllers
{
    [Authorize(Roles = nameof(RolesEnum.Administrator))]
    public class ProductController : BaseController
    {
        private readonly IProductService productService;

        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await productService.GetAllAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id != 0)
            {
                return View(nameof(Edit), await productService.GetAsync(id));
            }
            
            return View(nameof(Index));
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(nameof(Edit), productService.GetModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    await productService.AddAsync(model);
                    return RedirectToAction(nameof(Index));
                }

                await productService.EditAsync(model);
                return RedirectToAction(nameof(Index));
            }

            return View(nameof(Edit), model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await productService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

TestShop.Web/Controllers/ShopController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestShop.Application.ServiceInterfaces;

namespace TestShop.Web.Controllers
{
    [Authorize]
    public class ShopController : BaseController
    {
        private readonly IShopService shopService;

        public ShopController(IShopService shopService)
        {
            this.shopService = shopService;
        }

        public IActionResult Index()
        {
            return View(shopService.GetAllProductsAsync());
        }
    }
}

TestShop.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestShop.Application.Models.User;
using TestShop.Application.ServiceInterfaces;
using TestShop.CrossCutting.Enums;

namespace TestShop.Web.Controllers
{
    [Authorize(Roles = nameof(RolesEnum.Administrator))]
    public class UserController : BaseController
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await userService.GetAllAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            return View(await userService.GetAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEditModel model)
        {
            await userService.SetRoleAsync(model);
            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> Lock(UserLockModel model)
        {
            await userService.ChangeLockStatusAsync(model);
            return Ok();
        }
    }
}

TestShop.Web/Views/Shared/_Layout.cshtml
@using TestShop.CrossCutting.Enums
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && User.IsInRole(nameof(RolesEnum.Administrator)))
                        {
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link text-dark" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Administrator</a>
                                <div class="dropdown-content" aria-labelledby="navbarDropdownMenuLink">
                                    <a asp-controller="Product" asp-action="Index" class="text-dark">Products</a>
                                    <a asp-controller="User" asp-action="Index" class="text-dark">Users</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Shop" asp-action="Index">Shop</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TestShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-maskedinput/jquery.inputmask.js"></script>
    <environment include="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/app/modules/user/user.module.js" asp-append-version="true"></script>
        <script src="~/js/app/modules/user/user.index.module.js"></script>
        <script src="~/js/app/modules/user/user.edit.module.js"></script>
        <script src="~/js/app/modules/cart/cart.index.module.js"></script>
        <script src="~/js/app/modules/shop/shop.index.model.js"></script>
        <script src="~/js/app/modules/cart.history/cart.history.index.module.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>